// src/app/page.tsx
// ProjMgtAI Landing Page — v14.2 Multi-Page Pipeline
"use client";

import { useState, useRef, useCallback } from "react";
import Script from "next/script";

type ExtractorStatus = "idle" | "reading" | "classifying" | "extracting" | "building" | "done" | "error";

declare global {
  interface Window {
    pdfjsLib: any;
    XLSX: any;
  }
}

export default function HomePage() {
  const [file, setFile] = useState<File | null>(null);
  const [status, setStatus] = useState<ExtractorStatus>("idle");
  const [progress, setProgress] = useState("");
  const [error, setError] = useState("");
  const [resultUrl, setResultUrl] = useState<string | null>(null);
  const [stats, setStats] = useState<any>(null);
  const [pdfReady, setPdfReady] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    const dropped = e.dataTransfer.files[0];
    if (dropped?.type === "application/pdf") {
      setFile(dropped);
      setError("");
    } else {
      setError("Please drop a PDF file.");
    }
  }, []);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected) { setFile(selected); setError(""); }
  };

  // Extract text from PDF with page markers
  async function extractTextFromPdf(pdfFile: File): Promise<{ text: string; pageCount: number }> {
    const arrayBuffer = await pdfFile.arrayBuffer();
    const pdf = await window.pdfjsLib.getDocument({ data: arrayBuffer }).promise;
    const pages: string[] = [];

    for (let i = 1; i <= pdf.numPages; i++) {
      setProgress(`Reading page ${i} of ${pdf.numPages}...`);
      const page = await pdf.getPage(i);
      const content = await page.getTextContent();
      const text = content.items.map((item: any) => item.str).join(" ");
      pages.push(`--- PAGE ${i} ---\n${text}`);
    }

    return { text: pages.join("\n\n"), pageCount: pdf.numPages };
  }

  const handleExtract = async () => {
    if (!file || !pdfReady) return;

    setStatus("reading");
    setProgress("Extracting text from PDF...");
    setError("");
    setResultUrl(null);
    setStats(null);

    try {
      // Step 1: Extract text with page markers
      const { text: pdfText, pageCount } = await extractTextFromPdf(file);

      if (!pdfText || pdfText.trim().length < 10) {
        throw new Error("Could not extract text from PDF. This may be a scanned/image PDF.");
      }

      // Step 2: Send to v14.2 multi-page pipeline
      setStatus("extracting");
      setProgress(`Running v14.2 multi-page pipeline (${pageCount} pages, ${pdfText.length.toLocaleString()} chars)...`);

      const response = await fetch("/api/scope-extractor-v14", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: pdfText,
          projectId: file.name.replace(".pdf", ""),
          sheetRef: "multi-page",
        }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({ error: `HTTP ${response.status}` }));
        throw new Error(err.error || `Extraction failed (${response.status})`);
      }

      const result = await response.json();
      if (!result.ok) throw new Error(result.error || "Extraction returned no results");

      setStats(result.stats);

      // Step 3: Build multi-tab Excel
      setStatus("building");
      setProgress("Building Excel workbook...");

      const excelBlob = await buildExcel(result, file.name);
      const url = URL.createObjectURL(excelBlob);
      setResultUrl(url);
      setStatus("done");
      setProgress("");
    } catch (err: any) {
      setStatus("error");
      setError(err.message || "Something went wrong");
      setProgress("");
    }
  };

  // Build multi-tab Excel with per-room sheets
  async function buildExcel(result: any, filename: string): Promise<Blob> {
    const XLSX = await loadSheetJS();
    const wb = XLSX.utils.book_new();

    // ── Tab 1: Project Summary ──
    const summaryData: any[][] = [
      ["MILLWORK SHOP ORDER — Generated by ProjMgtAI v14.2"],
      [],
      ["Project:", result.projectId || filename],
      ["Document Type:", result.projectContext?.documentType || "unknown"],
      ["Model:", result.model || ""],
      ["Pipeline:", "v14.2 (multi-page: room grouping → cross-sheet context → per-room extraction)"],
      ["Pages Processed:", result.stats?.pageCount || 0],
      ["Rooms Detected:", result.stats?.roomCount || 0],
      [],
    ];

    // Material legend
    if (result.projectContext?.materialLegend?.length > 0) {
      summaryData.push(["RESOLVED MATERIAL SPECIFICATIONS"]);
      summaryData.push(["Code", "Manufacturer", "Product", "Catalog #", "Category"]);
      for (const m of result.projectContext.materialLegend) {
        summaryData.push([m.code, m.manufacturer, m.productName, m.catalogNumber, m.category]);
      }
      summaryData.push([]);
    }

    // Room summary
    summaryData.push(["ROOM EXTRACTION SUMMARY"]);
    summaryData.push(["Room", "Pages", "Items", "Assemblies", "Status", "LLM Time"]);
    const rooms = result.rooms || [];
    for (const r of rooms) {
      summaryData.push([
        r.room, (r.pages || []).join(", "), r.itemCount || 0,
        r.assemblyCount || 0, r.status || "",
        r.timing ? `${r.timing.llmMs}ms` : "",
      ]);
    }
    summaryData.push([]);

    // Timing
    summaryData.push(["PERFORMANCE"]);
    summaryData.push(["Pass 1 (context + grouping):", `${result.timing?.pass1Ms || 0}ms`]);
    summaryData.push(["Pass 3 (LLM extraction):", `${result.timing?.llmMs || 0}ms`]);
    summaryData.push(["Post-processing:", `${result.timing?.postprocessMs || 0}ms`]);
    summaryData.push(["Total:", `${result.timing?.totalMs || 0}ms`]);

    const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
    ws1["!cols"] = [{ wch: 32 }, { wch: 20 }, { wch: 25 }, { wch: 18 }, { wch: 15 }, { wch: 15 }];
    XLSX.utils.book_append_sheet(wb, ws1, "Project Summary");

    // ── Tab 2: All Items (master list) ──
    const allHeaders = [
      "#", "Room", "Type", "Description", "Section", "Qty", "Unit",
      "W (mm)", "D (mm)", "H (mm)", "Dim Source",
      "Material Code", "Material", "Hardware",
      "Confidence", "Notes"
    ];
    const allData = [allHeaders];
    const rows = result.rows || [];
    rows.forEach((r: any, i: number) => {
      allData.push([
        i + 1, r.room || "", r.item_type || "", r.description || "",
        r.section_id || "", r.qty || 1, r.unit || "EA",
        r.width_mm || "", r.depth_mm || "", r.height_mm || "", r.dim_source || "",
        r.material_code || "", r.material || "", r.hardware_spec || r.hardware_type || "",
        r.confidence || "", r.notes || "",
      ]);
    });
    const ws2 = XLSX.utils.aoa_to_sheet(allData);
    ws2["!cols"] = [
      { wch: 5 }, { wch: 20 }, { wch: 18 }, { wch: 45 }, { wch: 8 },
      { wch: 6 }, { wch: 6 }, { wch: 10 }, { wch: 10 }, { wch: 10 },
      { wch: 10 }, { wch: 12 }, { wch: 30 }, { wch: 30 }, { wch: 10 }, { wch: 40 },
    ];
    XLSX.utils.book_append_sheet(wb, ws2, "All Items");

    // ── Tabs 3+: Per-Room sheets ──
    const roomNames = [...new Set(rows.map((r: any) => r.room || "Unclassified"))];
    for (const roomName of roomNames) {
      const roomRows = rows.filter((r: any) => (r.room || "Unclassified") === roomName);
      if (roomRows.length === 0) continue;

      const roomData = [allHeaders];
      roomRows.forEach((r: any, i: number) => {
        roomData.push([
          i + 1, r.room || "", r.item_type || "", r.description || "",
          r.section_id || "", r.qty || 1, r.unit || "EA",
          r.width_mm || "", r.depth_mm || "", r.height_mm || "", r.dim_source || "",
          r.material_code || "", r.material || "", r.hardware_spec || r.hardware_type || "",
          r.confidence || "", r.notes || "",
        ]);
      });

      const wsRoom = XLSX.utils.aoa_to_sheet(roomData);
      wsRoom["!cols"] = ws2["!cols"];
      // Excel sheet names max 31 chars
      const sheetName = roomName.substring(0, 31).replace(/[\\/*?[\]:]/g, "");
      XLSX.utils.book_append_sheet(wb, wsRoom, sheetName);
    }

    // ── Warnings tab ──
    const warnData: any[][] = [["POST-PROCESSOR WARNINGS"], []];
    const warnings = result.warnings || [];
    if (warnings.length === 0) {
      warnData.push(["No warnings — all items validated."]);
    } else {
      for (const w of warnings) warnData.push([w]);
    }
    const wsWarn = XLSX.utils.aoa_to_sheet(warnData);
    XLSX.utils.book_append_sheet(wb, wsWarn, "Warnings");

    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
    return new Blob([wbout], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });
  }

  function loadSheetJS(): Promise<any> {
    return new Promise((resolve, reject) => {
      if (window.XLSX) { resolve(window.XLSX); return; }
      const script = document.createElement("script");
      script.src = "https://cdn.sheetjs.com/xlsx-0.20.1/package/dist/xlsx.full.min.js";
      script.onload = () => resolve(window.XLSX);
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  const reset = () => {
    setFile(null); setStatus("idle"); setProgress(""); setError("");
    if (resultUrl) URL.revokeObjectURL(resultUrl);
    setResultUrl(null); setStats(null);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  return (
    <main style={{
      minHeight: "100vh",
      background: "linear-gradient(168deg, #0a0e1a 0%, #0f1729 40%, #111d2e 100%)",
      color: "#e2e8f0",
      fontFamily: "'JetBrains Mono', 'SF Mono', 'Fira Code', monospace",
    }}>
      <Script
        src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"
        onLoad={() => {
          window.pdfjsLib.GlobalWorkerOptions.workerSrc =
            "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
          setPdfReady(true);
        }}
      />

      {/* Nav */}
      <nav style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 40px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <div style={{ width: 28, height: 28, background: "linear-gradient(135deg, #22d3ee, #6366f1)", borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 700, color: "#0a0e1a" }}>P</div>
          <span style={{ fontWeight: 700, fontSize: 16, letterSpacing: "-0.02em" }}>ProjMgtAI</span>
        </div>
        <div style={{ display: "flex", gap: "32px", fontSize: 13, opacity: 0.7 }}>
          <a href="#features" style={{ color: "inherit", textDecoration: "none" }}>Features</a>
          <a href="#try" style={{ color: "inherit", textDecoration: "none" }}>Try It</a>
          <span style={{ display: "inline-flex", alignItems: "center", gap: 6 }}>
            <span style={{ width: 7, height: 7, borderRadius: "50%", background: "#22c55e", display: "inline-block", boxShadow: "0 0 6px #22c55e" }} />
            v14.2 Live
          </span>
        </div>
      </nav>

      {/* Hero */}
      <section style={{ textAlign: "center", padding: "100px 20px 80px" }}>
        <div style={{ display: "inline-block", padding: "6px 16px", border: "1px solid rgba(34,211,238,0.3)", borderRadius: 20, fontSize: 12, color: "#22d3ee", marginBottom: 24, letterSpacing: "0.04em" }}>
          ★ v14.2 Multi-Page — Upload full plan sets
        </div>
        <h1 style={{ fontSize: "clamp(36px, 5vw, 64px)", fontWeight: 800, lineHeight: 1.1, letterSpacing: "-0.03em", margin: "0 0 20px", fontFamily: "'Inter', 'Helvetica Neue', sans-serif" }}>
          Full project takeoff,<br />
          <span style={{ background: "linear-gradient(135deg, #22d3ee, #6366f1, #a855f7)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
            every room, one click.
          </span>
        </h1>
        <p style={{ fontSize: 16, maxWidth: 520, margin: "0 auto 36px", lineHeight: 1.6, opacity: 0.7 }}>
          Upload multi-page architectural plan PDFs. AI auto-groups pages by room,
          resolves material specs across sheets, and extracts every cabinet, countertop,
          and hardware item — with manufacturer part numbers.
        </p>
        <a href="#try" style={{ padding: "12px 28px", background: "linear-gradient(135deg, #22d3ee, #6366f1)", color: "#0a0e1a", borderRadius: 8, fontWeight: 700, fontSize: 14, textDecoration: "none" }}>
          Try It Now →
        </a>
      </section>

      {/* Features */}
      <section id="features" style={{ padding: "60px 40px", textAlign: "center" }}>
        <div style={{ fontSize: 11, letterSpacing: "0.15em", textTransform: "uppercase", color: "#22d3ee", marginBottom: 12 }}>NEW IN V14.2</div>
        <h2 style={{ fontSize: 28, fontWeight: 700, fontFamily: "'Inter', sans-serif", marginBottom: 40 }}>
          Multi-page, multi-room extraction
        </h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 20, maxWidth: 900, margin: "0 auto" }}>
          {[
            { icon: "📑", title: "Multi-Page Upload", desc: "Upload 10-50 page PDFs. AI processes all pages in one pass." },
            { icon: "🏠", title: "Room Auto-Grouping", desc: "Pages automatically grouped by room from title block text." },
            { icon: "🔗", title: "Cross-Sheet Context", desc: "Material legend on page 1 resolves codes on pages 2-50." },
            { icon: "🏭", title: "Manufacturer Specs", desc: "Blum, Rev-A-Shelf, Wilsonart — full part numbers extracted." },
            { icon: "📋", title: "Per-Room Excel Tabs", desc: "One tab per room + master list + material legend + warnings." },
            { icon: "⚠️", title: "Scope Exclusions", desc: "N.I.C. and By Others items flagged but still visible for clarity." },
          ].map((f, i) => (
            <div key={i} style={{ padding: "28px 24px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 12, textAlign: "left" }}>
              <div style={{ fontSize: 24, marginBottom: 12 }}>{f.icon}</div>
              <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 6 }}>{f.title}</div>
              <div style={{ fontSize: 13, opacity: 0.6, lineHeight: 1.5 }}>{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Try It */}
      <section id="try" style={{ padding: "60px 40px 100px", textAlign: "center" }}>
        <div style={{ fontSize: 11, letterSpacing: "0.15em", textTransform: "uppercase", color: "#22d3ee", marginBottom: 12 }}>LIVE DEMO</div>
        <h2 style={{ fontSize: 28, fontWeight: 700, fontFamily: "'Inter', sans-serif", marginBottom: 12 }}>Upload your plan set</h2>
        <p style={{ opacity: 0.6, marginBottom: 32, fontSize: 14 }}>
          Drop a multi-page architectural PDF and get a complete shop order with per-room tabs.
        </p>

        <div style={{ maxWidth: 520, margin: "0 auto", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 16, padding: 32 }}>
          {status === "idle" && (
            <>
              <div onDrop={handleDrop} onDragOver={(e) => e.preventDefault()} onClick={() => fileInputRef.current?.click()}
                style={{ border: "2px dashed rgba(34,211,238,0.3)", borderRadius: 12, padding: "48px 24px", cursor: "pointer", transition: "border-color 0.2s", marginBottom: file ? 16 : 0 }}
                onMouseEnter={(e) => (e.currentTarget.style.borderColor = "rgba(34,211,238,0.6)")}
                onMouseLeave={(e) => (e.currentTarget.style.borderColor = "rgba(34,211,238,0.3)")}>
                <div style={{ fontSize: 32, marginBottom: 12 }}>📎</div>
                <div style={{ fontSize: 14, color: "#22d3ee", fontWeight: 600 }}>
                  Drop a PDF here <span style={{ opacity: 0.5, color: "#e2e8f0", fontWeight: 400 }}>or click to browse</span>
                </div>
                <div style={{ fontSize: 12, opacity: 0.4, marginTop: 8 }}>Supports multi-page plan sets (10-50+ pages)</div>
              </div>
              <input ref={fileInputRef} type="file" accept=".pdf" onChange={handleFileSelect} style={{ display: "none" }} />
              {file && (
                <div style={{ marginTop: 16 }}>
                  <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px", background: "rgba(34,211,238,0.08)", borderRadius: 8, marginBottom: 16 }}>
                    <span style={{ fontSize: 13 }}>📄 {file.name} <span style={{ opacity: 0.5 }}>({(file.size / 1024).toFixed(0)} KB)</span></span>
                    <button onClick={(e) => { e.stopPropagation(); reset(); }} style={{ background: "none", border: "none", color: "#ef4444", cursor: "pointer", fontSize: 13 }}>✕</button>
                  </div>
                  <button onClick={handleExtract} disabled={!pdfReady}
                    style={{ width: "100%", padding: "14px", background: pdfReady ? "linear-gradient(135deg, #22d3ee, #6366f1)" : "rgba(255,255,255,0.1)", color: "#0a0e1a", border: "none", borderRadius: 8, fontWeight: 700, fontSize: 15, cursor: pdfReady ? "pointer" : "wait", fontFamily: "inherit" }}>
                    {pdfReady ? "Extract All Rooms →" : "Loading PDF engine..."}
                  </button>
                </div>
              )}
            </>
          )}

          {(status === "reading" || status === "extracting" || status === "building") && (
            <div style={{ padding: "40px 0" }}>
              <div style={{ width: 48, height: 48, border: "3px solid rgba(34,211,238,0.2)", borderTop: "3px solid #22d3ee", borderRadius: "50%", margin: "0 auto 20px", animation: "spin 1s linear infinite" }} />
              <div style={{ fontSize: 14, fontWeight: 600 }}>{progress}</div>
              <div style={{ fontSize: 12, opacity: 0.5, marginTop: 8 }}>
                {status === "reading" && "Extracting text from each page..."}
                {status === "extracting" && "Pass 1: Context → Pass 2: Room grouping → Pass 3: Per-room extraction"}
                {status === "building" && "Building multi-tab Excel workbook..."}
              </div>
              <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
            </div>
          )}

          {status === "done" && resultUrl && (
            <div style={{ padding: "24px 0" }}>
              <div style={{ fontSize: 40, marginBottom: 16 }}>✅</div>
              <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 8 }}>Extraction Complete</div>
              {stats && (
                <div style={{ fontSize: 12, opacity: 0.6, marginBottom: 20, lineHeight: 1.8 }}>
                  {stats.pageCount} pages · {stats.roomCount} rooms · {stats.totalItems} items ·{" "}
                  {stats.withDimensions} with dims · {stats.materialLegendCount || 0} materials resolved
                  {stats.documentType !== "unknown" && ` · ${stats.documentType}`}
                </div>
              )}
              <a href={resultUrl} download={`shop_order_v142_${file?.name?.replace(".pdf", "")}.xlsx`}
                style={{ display: "inline-block", padding: "14px 32px", background: "linear-gradient(135deg, #22c55e, #16a34a)", color: "#fff", borderRadius: 8, fontWeight: 700, fontSize: 14, textDecoration: "none", marginBottom: 12 }}>
                ⬇ Download Excel ({stats?.roomCount || 0} room tabs)
              </a>
              <br />
              <button onClick={reset} style={{ background: "none", border: "1px solid rgba(255,255,255,0.15)", color: "#e2e8f0", padding: "10px 24px", borderRadius: 8, fontSize: 13, cursor: "pointer", marginTop: 8, fontFamily: "inherit" }}>
                Extract Another
              </button>
            </div>
          )}

          {status === "error" && (
            <div style={{ padding: "24px 0" }}>
              <div style={{ fontSize: 40, marginBottom: 16 }}>❌</div>
              <div style={{ fontSize: 14, fontWeight: 600, color: "#ef4444", marginBottom: 8 }}>{error}</div>
              <button onClick={reset} style={{ background: "none", border: "1px solid rgba(255,255,255,0.15)", color: "#e2e8f0", padding: "10px 24px", borderRadius: 8, fontSize: 13, cursor: "pointer", fontFamily: "inherit" }}>Try Again</button>
            </div>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer style={{ textAlign: "center", padding: "40px 20px", borderTop: "1px solid rgba(255,255,255,0.06)", fontSize: 12, opacity: 0.4 }}>
        © 2026 ProjMgtAI — Construction Intelligence, not guesswork.
      </footer>
    </main>
  );
}
