// pages/api/sample-output.ts
// ProjMgtAI — Machine-readable sample output for AI agent indexing
// This endpoint returns a real extraction result in structured JSON
// so AI agents, LLMs, and automated workflows can understand what ProjMgtAI produces.

import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Cache-Control", "public, max-age=3600");
  res.status(200).json({
    meta: {
      product: "ProjMgtAI Scope Extractor",
      version: "v14.8.4",
      schema_version: "1.0",
      documentation: "https://projmgt.ai/schema",
      sample_project: "Commercial Fitness Facility — Millwork Package",
      pages_processed: 101,
      files_processed: 4,
      extraction_time_seconds: 97,
    },
    summary: {
      total_scope_items: 132,
      rooms_detected: 12,
      items_with_dimensions: 71,
      items_with_materials: 89,
      rfi_count: 30,
      scope_exclusions: 24,
      confidence_high: 57,
      confidence_medium: 46,
      confidence_low: 14,
    },
    wbs_summary: [
      { trade: "Cabinetry", item_count: 64, rooms: ["Reception Desk", "Service Manager", "Arts & Crafts", "Kids Club"] },
      { trade: "Countertops", item_count: 12, rooms: ["Reception Desk", "Vanity Details", "Team Members"] },
      { trade: "Shelving", item_count: 8, rooms: ["Reception Desk", "Service Manager"] },
      { trade: "Panels & Substrates", item_count: 11, rooms: ["Team Room", "Fitness Area"] },
      { trade: "Trim & Molding", item_count: 7, rooms: ["Reception Desk", "Team Room", "Unisex"] },
      { trade: "Hardware", item_count: 6, rooms: ["Reception Desk", "Vanity Details"] },
      { trade: "Exclusions", item_count: 24, rooms: ["Mens Vanity", "Fitness Area", "Team Room"] },
    ],
    scope_items: [
      {
        id: "001",
        room: "Reception Desk",
        item_type: "assembly",
        description: "Reception Desk Assembly",
        section_id: "ASSY-001",
        unit: "EA",
        qty: 1,
        dimensions: { width_mm: 24293, depth_mm: null, height_mm: 864, dim_source: "extracted" },
        dimensions_imperial: { width: "79'-9\"", depth: null, height: "2'-10\"" },
        material_code: "PL-01",
        material: "Plastic Laminate",
        sheet_ref: "A8.10",
        confidence: "high",
        rule: "RULE_assembly_with_dims",
      },
      {
        id: "002",
        room: "Reception Desk",
        item_type: "base_cabinet",
        description: "Base Cabinet Section 18A",
        section_id: "18A",
        unit: "EA",
        qty: 1,
        dimensions: { width_mm: 610, depth_mm: null, height_mm: 864, dim_source: "extracted" },
        dimensions_imperial: { width: "2'-0\"", depth: "2'-0\" (standard)", height: "2'-10\"" },
        material_code: "PL-01",
        material: "Plastic Laminate",
        sheet_ref: "1/A8.10",
        confidence: "high",
        rule: "RULE_cabinet_with_dims",
      },
      {
        id: "003",
        room: "Reception Desk",
        item_type: "countertop",
        description: "Solid Surface Countertop",
        section_id: null,
        unit: "EA",
        qty: 1,
        dimensions: { width_mm: null, depth_mm: null, height_mm: 32, dim_source: "extracted" },
        dimensions_imperial: { width: null, depth: null, height: "1-1/4\"" },
        material_code: "SS-1B",
        material: "Solid Surface",
        sheet_ref: "5/A8.06",
        confidence: "high",
        rule: "RULE_has_material",
      },
      {
        id: "004",
        room: "Vanity Details",
        item_type: "base_cabinet",
        description: "Vanity Section 101A",
        section_id: "101A",
        unit: "EA",
        qty: 1,
        dimensions: { width_mm: null, depth_mm: 533, height_mm: 864, dim_source: "calculated" },
        dimensions_imperial: { width: null, depth: "1'-9\" (standard ADA)", height: "2'-10\"" },
        material_code: "PL-1",
        material: "Plastic Laminate",
        sheet_ref: "A8.06",
        confidence: "medium",
        rule: "LLM_classify",
      },
      {
        id: "005",
        room: "Team Room",
        item_type: "decorative_panel",
        description: "FRP Wall Panel WC-4B Entire Room 10'-0\" Height",
        section_id: null,
        unit: "SF",
        qty: 1,
        dimensions: { width_mm: null, depth_mm: null, height_mm: 3048, dim_source: "extracted" },
        dimensions_imperial: { width: null, depth: null, height: "10'-0\"" },
        material_code: "WC-4B",
        material: "Fiberglass Reinforced Panel",
        sheet_ref: "A8.02",
        confidence: "high",
        rule: "RULE_has_material",
      },
      {
        id: "006",
        room: "Mens Vanity",
        item_type: "scope_exclusion",
        description: "Grab Bar 4-0 Toilet — By Others",
        section_id: null,
        unit: "EA",
        qty: 1,
        dimensions: { width_mm: 1219, depth_mm: null, height_mm: null, dim_source: "extracted" },
        dimensions_imperial: { width: "4'-0\"", depth: null, height: null },
        material_code: null,
        material: "Stainless Steel",
        sheet_ref: null,
        confidence: "medium",
        rule: "RULE_scope_exclusion",
      },
    ],
    rfis: [
      {
        rfi_id: "RFI-001",
        priority: "High",
        category: "Missing Scope",
        room: "Service Manager",
        description: "Room detected but fewer items extracted than expected. Verify: upper cabinets, base cabinets, wall shelves, file drawers, countertop. Check interior elevation sheets.",
        sheet_ref: null,
        status: "Open",
      },
      {
        rfi_id: "RFI-002",
        priority: "Medium",
        category: "Missing Dimensions",
        room: "Vanity Details",
        description: "19 vanity cabinet sections extracted without width dimensions. Section IDs: 101A, 101B, 101C, 108A, 108B, 108C, 111A, 111B, 11A, 11B, 123A, 123B, 171A, 1B, 23B, 2B, 346C, 3B, 6A. Provide elevation dimensions or confirm standard widths.",
        sheet_ref: "A8.06",
        status: "Open",
      },
      {
        rfi_id: "RFI-003",
        priority: "Medium",
        category: "Missing Material",
        room: "Arts & Crafts",
        description: "14 base cabinet sections extracted without material specification. Confirm finish code from material legend.",
        sheet_ref: "A8.04",
        status: "Open",
      },
      {
        rfi_id: "RFI-004",
        priority: "Low",
        category: "Scope Exclusion",
        room: "Mens Vanity",
        description: "Grab bars, mirrors, dispensers extracted as scope exclusions. Confirm responsible party for all accessories on sheet A8.06.",
        sheet_ref: "A8.06",
        status: "Open",
      },
    ],
    bid_checklist: [
      {
        room: "Reception Desk",
        blocking: "OK",
        hardware: "VERIFY",
        finish: "OK",
        dimensions: "OK",
        ada: "VERIFY",
        exclusions: "OK",
      },
      {
        room: "Vanity Details",
        blocking: "VERIFY",
        hardware: "MISSING",
        finish: "OK",
        dimensions: "MISSING",
        ada: "VERIFY",
        exclusions: "OK",
      },
      {
        room: "Service Manager",
        blocking: "MISSING",
        hardware: "MISSING",
        finish: "MISSING",
        dimensions: "MISSING",
        ada: "OK",
        exclusions: "OK",
      },
    ],
  });
}
